name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.4
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.1
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  on_audio_query: ^2.9.0
  objectbox: ^2.5.0
  objectbox_flutter_libs: any
  path: ^1.9.0
  json_serializable: ^6.7.1
  just_audio_background: ^0.0.1-beta.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  freezed: ^2.4.7
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
   - assets/image/ 
   - assets/icon/
   - assets/gif/ 
   - assets/song/song1.mp3 
